[tool.poetry]
name = "devopstest"
authors = ["maor"]
version = "1.0"
description = "none"
license = "GPL-3.0-or-later"
[tool.poetry.dependencies]
python = "^3.7"
elasticsearch = "7.13.4"
pandas = "1.1.5"
retry = "^0.9.2"